### ISSUE TITLE
Recent contact disappearing after refresh. 

### ISSUE THREAD

**Issue by Bharath-kandula** [ldvlgr/recent-contacts-plugin#1]
Hi, 
the code works well. But if we refresh the browser or sign out and sign back into the application the history is disappearing. How do I keep the data? Thanks.

**Comment by ldvlgr** [comment]
This plugin was updated to persist the Contact History list to the browser localStorage.  The Redux store will be re-initialized with the list from localStorage upon log-in or browser refresh
